"""“ref_key”

Revision ID: d157b6689a0c
Revises: afa2f57343f3
Create Date: 2024-02-09 16:31:55.035046

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd157b6689a0c'
down_revision: Union[str, None] = 'afa2f57343f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('users_referral_fkey'), 'users', 'referral_codes', ['referral'], ['code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('users_referral_fkey'), 'users', type_='foreignkey')
    # ### end Alembic commands ###
